services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - PLEX_CLAIM=claim-hha4f2LNof_Fg-sUs8WS
    network_mode: host
    volumes:
      - /home/plex/config:/config
      - /home/plex/transcode:/transcode
      - /home/plex/data:/data
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    volumes:
      - /home/sonarr/config:/config
      - /home/plex/data/TV:/tv #optional
      - /home/plex/data/Movies:/movies #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  flareSolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flareSolverr
    environment:
      - LOG_LEVEL=info
    ports:
      - 8191:8191
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/transmission/data:/config
      - /home/transmission/downloads:/downloads #optional
      - /home/transmission/watch:/watch #optional
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped